#!/usr/bin/env bash
# Install nginx
apt-get -y update
apt-get -y install nginx
mv /usr/share/nginx/html/index.html /usr/share/nginx/html/index.txt
echo "Hello World" > /usr/share/nginx/html/index.html
service nginx restart
