#!/usr/bin/env bash
# Make `/redirect_me` redirect to another site
apt-get -y update && apt-get -y upgrade
apt-get -y install nginx
new="localhost;\n\tlocation \/redirect_me{\n\t\treturn 301 http:\/\/www.google.com;}"
sed -i "s/localhost;/$new/" /etc/nginx/sites-available/default
sudo service nginx restart
