#!/usr/bin/env bash
# Make `/redirect_me` redirect to another site
apt-get -y update && apt-get -y upgrade
apt-get -y install nginx
new="34.138.244.202;\n\tlocation \/redirect_me{\n\t\treturn 301 http:\/\/www.google.com;}"
sed -i "s/localhost;/$new/" /etc/nginx/sites-available/default
sed -i "s/#error_page 404/error_page 404/" /etc/nginx/sites-available/default
touch /usr/share/nginx/html/404.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
service nginx restart
