#!/usr/bin/env bash
# install nginx and set up custom headers
sudo apt-get -y update && sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo sed -i "29i \\\tadd_header X-Served-By $HOSTNAME;\n" /etc/nginx/sites-available/default
sudo service nginx restart
