#!/usr/bin/env bash
# install and configure HAproxy on lb-01 server
sudo apt-get -y update && sudo apt-get -y upgrade
sudo apt-get -y install haproxy=2.4.\*

sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
sudo echo -e "\nfrontend localnodes\n\tbind *:80\n\tmode: http\n\tdefault_backend nodes\n\n\nbackend nodes\n\tbalance roundrobin\n\tserver 768-web-01 34.73.91.123:80 check\n\tserver 768-web-02 34.204.191.36:80 check\n" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
