#!/usr/bin/env bash
#Display 'To infinity and beyond', if kill attempt 'I am invincible!!!'
trap 'echo "I am invincible!!!"' SIGTERM
counter=2
while [ $counter -gt 0 ]; do
    echo "To infinity and beyond"
    sleep 2
done