#!/usr/bin/env bash
#Display 'Bad luck' when counter = 4, 'Good Luck' when counter = 8 else Best School
counter=1
while [ $counter -lt 11 ]; do
    if [ $counter -eq 4 ]
    then
        echo "bad luck"
    elif [ $counter -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    (( counter=counter+1 ))
done
