#!/usr/bin/env bash
#Display numbers from 1 to 20 and messages at counter = 4, 8 and 17
counter=1
while [ $counter -lt 21 ]; do
    echo $counter
    case "$counter" in
        "4")
            echo "bad luck from China"
            ;;
        "9")
            echo "bad luck from Japan"
            ;;
        "17")
            echo "bad luck from Italy"
            ;;
    esac
    (( counter+=1 ))
done
