#!/usr/bin/env bash

#run nginx as nginx

file="/etc/nginx/sites-available/default"
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i 's/listen .*::.* default_server;/listen [::]:8080 default_server;/' $file
sed -i '/:/!s/listen .*/listen 8080 default_server;/' $file
pkill apache2
chmod 777 /etc/nginx/nginx.conf
#sudo adduser --nginx  --no-create-home --disabled-login --disabled-password --group nginx
sudo -u nginx service nginx start
